---
- name: Wait for ssh connection
  hosts: all
  gather_facts: False
  tasks:
    - name: Ensure ssh port open
      wait_for:
        port: 22
        delay: 10
        timeout: 60
        search_regex: OpenSSH
        host: '{{(ansible_ssh_host|default(ansible_host))|default(inventory_hostname)}}'
      vars:
        ansible_connection: local

- name: Configure webser for deploy
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start Docker daemon
      systemd:
        name: docker
        state: started

    - name: Wait for Docker to start
      wait_for:
        host: localhost
        port: 2375
        delay: 20
        timeout: 150

    - name: Install Docker Python module
      pip:
        name: docker

    - name: Add ec2-user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: magharyta
        password: "{{ docker_password }}"

    - name: Run Java-Maven app container
      docker_container:
        name: java-maven-app
        image: "magharyta/my-repo:{{ docker_image }}"
        state: started
        restart: true
        ports:
          - "8080:8080"

